# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sdl-parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sdl-parking
  pod ‘SmartDeviceLink’, ‘~> 6.3.1’

end
